---

name: Test
on:
  push:
    paths-ignore:
      - 'data/**'
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Rust (stable)
        run: |
          rustup update stable
          rustup component add rustfmt
          rustup component add clippy

      - name: Check formatting
        run: cargo fmt --check

      - name: Check Clippy
        run: cargo clippy -- -Dwarnings

      - name: Run tests
        run: cargo test
