name: Updater
  
on:
  workflow_dispatch:
  # schedule:
  #   - cron: 0 */2 * * *

jobs:
  github:
    name: GitHub
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust (stable)
        run: |
          rustup update stable

      - name: Build the updater
        run: cargo build --release

      - name: Run the updater
        run: ./ci-update.sh
        env:
          DEPLOY_KEY: "${{ secrets.DEPLOY_KEY }}"
          GH_TOKENS: "${{ secrets.GH_TOKENS }}"
          RUST_LOG: "info"
          RUST_REPOS_TIMEOUT: 3601  # 1 hours
